### ISSUE TITLE
Size limits?

### ISSUE THREAD

**Issue by chrgraefe** [SharpGrip/FileSystem#1]
Hi,

cool project with nice architetcual implementation.
What file size have you tested with? Is there any limitation you are aware of.

I mean file sizes above 10GB.

kind regards

**Comment by mvdgun** [comment]
Thanks! I have not tested the adapters with large file sizes. Most of my tests were files up to 100MB. I am planning to test all the adapters with large file sizes soon.

As soon as I have test results I'll post them back here.

**Comment by mvdgun** [comment]
Closing this one as I don't have the time to properly document it. For size limits, please refer to the underlying client adapter documentation.
