### ISSUE TITLE
Issue reading directory with local file system on windows

### ISSUE THREAD

**Issue by elgransan** [SharpGrip/FileSystem#24]
Hi, I'm having a problem reading a directory with local file system on windows. It's linking the path 2 times

![image](https://github.com/SharpGrip/FileSystem/assets/9949584/bfe81123-6abe-48f5-9fd9-841ff6b7aca3)

**Comment by elgransan** [comment]
Yes, it's working with forward slashes!

**Comment by mvdgun** [comment]
Hi @elgransan, I tried looking into fixing the path normalization in the v1.0 version but unfortunately it's harder than expected. This issue will be fixed in the v1.1 release.

**Comment by mvdgun** [comment]
Hi @elgransan, I just released v1.1 of the library which fixes (among several other things) your forward slashes issue.
