### ISSUE TITLE
external configuration planned?

### ISSUE THREAD

**Issue by chrgraefe** [SharpGrip/FileSystem#4]
Hi,

nice tool with a flexibel code base.
Are there any plans to provide a file based configuration system with a services which is processing this configurations?

kind regards

**Comment by mvdgun** [comment]
Hi, not exactly sure what you mean. Could you give me an example of what you would like to see?

**Comment by mvdgun** [comment]
I'm closing this one since I haven't got back any reply. Feel free to open a new issue if you have any questions!
