### ISSUE TITLE
IDirectory doesn't have the virtual path

### ISSUE THREAD

**Issue by elgransan** [SharpGrip/FileSystem#5]
Hi, I'm trying to use the FileSystem and I have the problem that the LocalAdapter for IDirectory is returning the real path instead the virtual one, so if I want to do this, I can't:

        var modulesInstalled = _fileSystem.GetDirectories("default://Installed");
        foreach (var folder in modulesInstalled)
        {
            foreach (var file in _fileSystem.GetFiles(folder.Path))  // invalid path because is the absolute path, not the virtual one
            {
                 ... dealing with files ....
            }
        }

I'm not sure if the problem also applies to IFile

Maybe the IDirectory and IFile could have both, virtual and real paths

**Comment by mvdgun** [comment]
Hey! Thanks for reporting, sounds like a legit use case. Will look into this one and report back.

**Comment by elgransan** [comment]
Thank you, I really like the file system abstraction you did!

**Comment by mvdgun** [comment]
I just finished the implementation of the virtual path in the core library. Currently working out some adapter specific issues, as soon as those issues are fixed I will publish a new beta release.

**Comment by elgransan** [comment]
Awesome

**Comment by elgransan** [comment]
Thanks a lot, I will get a try!
